### PR TITLE
added answers

### PR DESCRIPTION
**Pull request by rktr95**
added answer.md file

### CODE REVIEW

**Review by niksmac — COMMENTED** [review]
Give us a few days to get back to you on this. Looks good 👍

**Comment by niksmac** [comment]
Hey @ajinkabeer Can you please review this?

**Comment by ajinkabeer** [comment]
Sure

**Comment by ajinkabeer** [comment]
All the solutions work just fine 👍
@niksmac

**Review by ajinkabeer — COMMENTED** [review]
The solutions work just fine. Good work!

Here's a good blog post on why not to use `var` anymore. 
https://hackernoon.com/why-you-shouldnt-use-var-anymore-f109a58b9b70

**Review by ajinkabeer — APPROVED** [review]

**Comment by niksmac** [comment]
Hey @rktr95 Please send your contact details to `careers at lightrains dot com`

**Pull request closed without merging**
